### ISSUE TITLE
Error getting token part 2

### ISSUE THREAD

**Issue by tpcolson** [Esri/developer-support#345]
Similar to https://github.com/Esri/developer-support/issues/280, I'm getting 

Traceback (most recent call last):
  File "C:\Temp\NEXRAD_PYTHON\update-Tiles-From-TPK\update-Tiles-From-TPK\OverWriteTilePackage.py", line 83, in <module>
    token= getToken(user, pw)
  File "C:\Temp\NEXRAD_PYTHON\update-Tiles-From-TPK\update-Tiles-From-TPK\OverWriteTilePackage.py", line 26, in getToken
    return jres['token'],jres['ssl']
KeyError: 'token'

{"error":{"code":400,"message":"Unable to generate token.","details":["'username' must be specified.","'password' must be specified."]}}

Despite using the same, correct username and pw that I can login to AGOL successfully, so the **issue IS NOT incorrect username or pw.**

**Comment by tpcolson** [comment]
https://github.com/Esri/developer-support/tree/master/python/general-python/update-tile-service-from-tpk

**Comment by jgravois** [comment]
the error seems to indicate that a username and/or password aren't making it through in the request at all.
